name: build-figures
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python src/pipeline.py
      - uses: actions/upload-artifact@v4
        with:
          name: figures
          path: figures/*
